/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.it_fionn.blacky_handyman

import com.it_fionn.blacky_handyman.config.Configuration

class App {
    fun run() {
        val blacky_handyman = BlackyHandyman(
            config = Configuration.load()
        )

        blacky_handyman.start()
    }
}

fun main() {
    App().run()
}
